### ISSUE TITLE
Dashboard for DLO is not working

### ISSUE THREAD

**Issue by taifur-bau** [road86/bahis-dash#1]
In dev web portal, I created a user for District Livestock Officer (DLO) , Barishal. username is _dlobarisal_. I have assigned catchment, I changed the access control for that role and provided access to the form summary, disease trend graph. After signing in with that username, _dlobarisal_, the dashboard not showing the expected menus.

**Comment by mixmixmix** [comment]
@taifur-bau if it doesn't work, please talk to @yokat and @WaliZaman to discuss what we can show on our dashboard instead.

**Comment by taifur-bau** [comment]
Yes, menus are rightly accessible now and your second point is right. If you make the dropdown of the geo (District for example for DLO accounts) unselectable then we may get the desired output. Currently the pointer is changing while hovering on the district dropdown list but it is still selectable. Make it completely unselectable.

**Comment by mixmixmix** [comment]
This issue realtes to our main bahis app, not to this standalone dashboard. I'll close it here (this is a *public* repository) an please reopen in https://github.com/road86/project-bahis/ if it is still relevant.
Thanks!
