### ISSUE TITLE
include biosafety and antimicrobial reports (consists of several tasks)

### ISSUE THREAD

**Issue by yokat** [road86/bahis-dash#11]
### Bug Description

A bug happened!

### To Reproduce

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error.

**Comment by ChasNelson1990** [comment]
This issue is just the template. Please edit the initial post or mark as closed.

**Comment by yokat** [comment]
biosafety added, form need to be checked
antimicrobial assessment needs "better" data
