### ISSUE TITLE
Split poultry and large animal reports

### ISSUE THREAD

**Issue by ChasNelson1990** [road86/bahis-dash#118]
### Problem

At the moment both poultry and large animals are shown on the "Reports" tab of the DLS page. This is not always useful for DLS and Epi people.

### Desired Solution

We want to replace this with two new tabs - one for "Large Animals" and one for "Poultry".

This should map correctly to the map and also to the "Diseases" drop down, i.e. no anthrax for poultry and no avian influenza for large animals.

**Comment by yokat** [comment]
Partially solved. Remaining task:
disease list does not change accordingly yet.

**Comment by yokat** [comment]
fixed
