### ISSUE TITLE
ULO landing page

### ISSUE THREAD

**Issue by yokat** [road86/bahis-dash#139]
### Problem

There is no dedicated page for ULO officers once they are behind the oauth. Also, the majority of possibilities should be deactivated for them

### Desired Solution

Having a page like DLO, but without the map. 
On the right: reports and No of sick and dead
On the left: Monthly comparison

**Comment by ChasNelson1990** [comment]
The url should follow the pattern: httpd://dashboard.com/{geo_id} or something like that
