### ISSUE TITLE
Group diseases for "Disease Case Numbers" report

### ISSUE THREAD

**Issue by yokat** [road86/bahis-dash#14]
### Bug Description

Diseases are to be clustered. e.g internal parasites. Please provide list of groupings.

### To Reproduce

4. See error.

**Comment by taifur-bau** [comment]
[Disease list.xlsx](https://github.com/road86/bahis-dash/files/10455949/Disease.list.xlsx)
Disease category list (internal parasite, external parasite, and protozoal diseases) attached. We need to create another report tab named "Zoonotic diseases". I have mentioned zoonotic diseases in the list.

**Comment by yokat** [comment]
Zoonotic diseases

**Comment by yokat** [comment]
exclude zoonotic disease and put into extra tab/report only for zoonotic disease, and only for the top 10 view

**Comment by yokat** [comment]
done, but needs streamlining for timing, but belongs to https://github.com/road86/bahis-dash/issues/8in
