### ISSUE TITLE
Database: Diseases contain wrong entries

### ISSUE THREAD

**Issue by yokat** [road86/bahis-dash#15]
### Bug Description

Listed diseases contain wrong entries.

### To Reproduce

4. See error.

**Comment by yokat** [comment]
Acetonaemia(Ketosis)
Actinobacillosis
Actinomycosis
Aflatoxicosis
Alkaloid Poisoning
Anaplasmosis
Anthrax
Arthritis
Aspergillosis
Aspiration Pneumonia
Atresi Ani
Avian Influenza
Avian Leukosis
Avitaminosis
Babesiosis
Balanoposthitis
Black Quarter (BQ)
Blue Tongue
Bottle Jaw
Botulism
Bovine Respiratory Disease Complex
Bovine Tuberculosis
Bovinerespiratory Disease Complex
Brucellosis
Burn
Calf Diphtheria
Calf Pheumonia
Calf Scour
Cho Engorgement
Chronic Respiratory Disease (CRD)
Classical Swine fever
Coccidiosis
Colibacillosis (E. coli Infection)
Colic
Contagious Caprine Pleuropneumonia
Cud Drop Syndrome
Cyst Under Skin
Dermatomycosis
Dermatophilosis
Dermoid Cyst
Downers Cow Syndroms
Duck Cholera
Duck Plague (Duck Enteritis Virus)
Dystocia
Egg Drop Syndrome (EDS)
Ephemeral Fever
Eye Worm Infection
Feline Panleukopenia
Foot and Mouth Disease (FMD)
Foot rot
Fowl Cholera
Fowl Pox
Fracture
Gangrene
Gangrenous Dermatitis
Gid Disease (Cerebral coenurosis)
Goat Pox
Hemorrhagic Septicemia (HS)
Hump Sore
Hypomagnesemia/Grass Tetany
Infectious Bursal Disease (IBD)
Infectious Coryza
Infectious Laryngotracheitis Virus (ILT)
Lead Poisoning
Lice Infestation
Listeriosis
Liver Fluke
Lumpy Skin Disease (LSD)
Lumpy Skin Disease(Lsd)
M2Aract
Malnutrition
Mastitis
Metritis
Milk Fever
Mite Infestation
Mycoplasmosis
Navel Ill
Necrotic Enteritis
Newcastle Disease
Nitrate Poisoning
Organophosphorus Poisoning
Other
Ovarian Cyst
Papiloma On Skin
Paramphistomum
Paraphimosis
Pesti des Petits Ruminants
Phymosis
Pneumonia
Pseudocowpox
Pyometra
Rabies
Retained Placenta
Rickets /Weak Calf Syndrome
Ringworm (Dermatophytosis)
Round Worm
Ruminal Tympany/ Bloat
s Disease (Paratuberculosis)"]
s Disease"]
Salmonella
Salmonellosis
Selenium Deficiency
Sheep Pox
Simple Indigestion
Stringhalt
Subcutaneous Cyst
Tape Worm
Teat Sore
Tetanus
Theileriosis
Tick Infestation
Toxoplasmosis
Trypanosomiasis
Umbilical Hernia
Unknown
Upward Patellar Fixation
Urea Poisoning
Urolithiasis
Utero Vaginal Prolapse
Verminous Pneumonia
Warts/Papillomatosis
Worm Infestation

**Comment by yokat** [comment]
with values:
-1 | Unknown
0 | Other
1 | Aflatoxicosis
2 | Anaplasmosis
3 | Anthrax
4 | Aspergillosis
5 | Avian Influenza
6 | Avian Leukosis
7 | Avitaminosis
8 | Babesiosis
9 | Black Quarter (BQ)
10 | Bovine Tuberculosis
11 | Brucellosis
12 | Calf Scour
13 | Chronic Respiratory Disease (CRD)
14 | Coccidiosis
15 | Colibacillosis (E. coli Infection)
16 | Contagious Caprine Pleuropneumonia
17 | Dermatophilosis
18 | Duck Cholera
19 | Duck Plague (Duck Enteritis Virus)
20 | Egg Drop Syndrome (EDS)
21 | Ephemeral Fever
22 | Foot and Mouth Disease (FMD)
23 | Foot rot
24 | Fowl Cholera
25 | Fowl Pox
26 | Gangrene
27 | Gangrenous Dermatitis
28 | Gid Disease (Cerebral coenurosis)
29 | Goat Pox
30 | Hemorrhagic Septicemia (HS)
31 | Hump Sore
32 | Infectious Bursal Disease (IBD)
33 | Infectious Coryza
34 | Infectious Laryngotracheitis Virus (ILT)
36 | Lice Infestation
37 | Liver Fluke
38 | Malnutrition
40 | Mastitis
41 | Milk Fever
42 | Mite Infestation
43 | Mycoplasmosis
44 | Navel Ill
45 | Necrotic Enteritis
46 | Newcastle Disease
47 | Pesti des Petits Ruminants
48 | Rabies
49 | Ringworm (Dermatophytosis)
50 | Round Worm
51 | Ruminal Tympany/ Bloat
52 | Salmonellosis
53 | Sheep Pox
54 | Stringhalt
55 | Tape Worm
56 | Teat Sore
57 | Tetanus
58 | Theileriosis
59 | Tick Infestation
60 | Worm Infestation
62 | Lumpy Skin Disease (LSD)
63 | Aspiration Pneumonia
64 | Classical Swine fever
66 | Feline Panleukopenia
67 | Pneumonia
Acetonaemia(Ketosis) | Acetonaemia(Ketosis)
Actinobacillosis | Actinobacillosis
Actinomycosis | Actinomycosis
Alkaloid Poisoning | Alkaloid Poisoning
Arthritis | Arthritis
Atresi Ani | Atresi Ani
Balanoposthitis | Balanoposthitis
Blue Tongue | Blue Tongue
Bottle Jaw | Bottle Jaw
Botulism | Botulism
Bovine Respiratory Disease Complex | Bovine Respiratory Disease Complex
Bovinerespiratory Disease Complex | Bovinerespiratory Disease Complex
Burn | Burn
Calf Diphtheria | Calf Diphtheria
Calf Pheumonia | Calf Pheumonia
Cho Engorgement | Cho Engorgement
Colic | Colic
Cud Drop Syndrome | Cud Drop Syndrome
Cyst Under Skin | Cyst Under Skin
Dermatomycosis | Dermatomycosis
Dermoid Cyst | Dermoid Cyst
Downers Cow Syndroms | Downers Cow Syndroms
Dystocia | Dystocia
Eye Worm Infection | Eye Worm Infection
Fracture | Fracture
Hypomagnesemia/Grass Tetany | Hypomagnesemia/Grass Tetany
Lead Poisoning | Lead Poisoning
Listeriosis | Listeriosis
Lumpy Skin Disease(Lsd) | Lumpy Skin Disease(Lsd)
M2Aract | M2Aract
Metritis | Metritis
Nitrate Poisoning | Nitrate Poisoning
Organophosphorus Poisoning | Organophosphorus Poisoning
Ovarian Cyst | Ovarian Cyst
Papiloma On Skin | Papiloma On Skin
Paramphistomum | Paramphistomum
Paraphimosis | Paraphimosis
Phymosis | Phymosis
Pseudocowpox | Pseudocowpox
Pyometra | Pyometra
Retained Placenta | Retained Placenta
Rickets /Weak Calf Syndrome | Rickets /Weak Calf Syndrome
s Disease (Paratuberculosis)"] | s Disease (Paratuberculosis)"]
s Disease"] | s Disease"]
Salmonella | Salmonella
Selenium Deficiency | Selenium Deficiency
Simple Indigestion | Simple Indigestion
Subcutaneous Cyst | Subcutaneous Cyst
Toxoplasmosis | Toxoplasmosis
Trypanosomiasis | Trypanosomiasis
Umbilical Hernia | Umbilical Hernia
Upward Patellar Fixation | Upward Patellar Fixation
Urea Poisoning | Urea Poisoning
Urolithiasis | Urolithiasis
Utero Vaginal Prolapse | Utero Vaginal Prolapse
Verminous Pneumonia | Verminous Pneumonia
Warts/Papillomatosis | Warts/Papillomatosis

And an empty value

**Comment by yokat** [comment]
Buffalo | 0 | Other
Cattle | 0 | Other
Goat | 0 | Other
Sheep | 0 | Other
Horse | 0 | Other
Cat | 0 | Other
Dog | 0 | Other
Pig | 0 | Others
Chicken | 0 | Others
Duck | 0 | Others
Goose | 0 | Others
Myna | 0 | Others
Pigeon | 0 | Others
Quail | 0 | Others
Turkey | 0 | Others
Rabbit | 0 | Others
Chicken | 1 | Aflatoxicosis
Duck | 1 | Aflatoxicosis
Goose | 1 | Aflatoxicosis
Myna | 1 | Aflatoxicosis
Pigeon | 1 | Aflatoxicosis
Quail | 1 | Aflatoxicosis
Turkey | 1 | Aflatoxicosis
Buffalo | 2 | Anaplasmosis
Cattle | 2 | Anaplasmosis
Goat | 2 | Anaplasmosis
Sheep | 2 | Anaplasmosis
Horse | 2 | Anaplasmosis
Cat | 2 | Anaplasmosis
Dog | 2 | Anaplasmosis
Pig | 2 | Anaplasmosis
Buffalo | 3 | Anthrax
Cattle | 3 | Anthrax
Goat | 3 | Anthrax
Sheep | 3 | Anthrax
Horse | 3 | Anthrax
Pig | 3 | Anthrax
Chicken | 4 | Aspergillosis
Duck | 4 | Aspergillosis
Goose | 4 | Aspergillosis
Moyana | 4 | Aspergillosis
Pegion | 4 | Aspergillosis
Quail | 4 | Aspergillosis
Turkey | 4 | Aspergillosis
Chicken | 5 | Avian Influenza
Duck | 5 | Avian Influenza
Goose | 5 | Avian Influenza
Myna | 5 | Avian Influenza
Pigeon | 5 | Avian Influenza
Quail | 5 | Avian Influenza
Turkey | 5 | Avian Influenza
Chicken | 6 | Avian Leukosis
Duck | 6 | Avian Leukosis
Goose | 6 | Avian Leukosis
Myna | 6 | Avian Leukosis
Pigeon | 6 | Avian Leukosis
Quail | 6 | Avian Leukosis
Turkey | 6 | Avian Leukosis
Chicken | 7 | Avitaminosis
Duck | 7 | Avitaminosis
Goose | 7 | Avitaminosis
Myna | 7 | Avitaminosis
Pigeon | 7 | Avitaminosis
Quail | 7 | Avitaminosis
Turkey | 7 | Avitaminosis
Buffalo | 8 | Babesiosis
Cattle | 8 | Babesiosis
Goat | 8 | Babesiosis
Sheep | 8 | Babesiosis
Horse | 8 | Babesiosis
Cat | 8 | Babesiosis
Dog | 8 | Babesiosis
Pig | 8 | Babesiosis
Buffalo | 9 | Black Quarter (BQ)
Cattle | 9 | Black Quarter (BQ)
Goat | 9 | Black Quarter (BQ)
Sheep | 9 | Black Quarter (BQ)
Buffalo | 10 | Bovine Tuberculosis
Cattle | 10 | Bovine Tuberculosis
Buffalo | 11 | Brucellosis
Cattle | 11 | Brucellosis
Goat | 11 | Brucellosis
Sheep | 11 | Brucellosis
Horse | 11 | Brucellosis
Cat | 11 | Brucellosis
Dog | 11 | Brucellosis
Pig | 11 | Brucellosis
Cattle | 12 | Calf Scour
Chicken | 13 | Chronic Respiratory Disease (CRD)
Duck | 13 | Chronic Respiratory Disease (CRD)
Goose | 13 | Chronic Respiratory Disease (CRD)
Myna | 13 | Chronic Respiratory Disease (CRD)
Pigeon | 13 | Chronic Respiratory Disease (CRD)
Quail | 13 | Chronic Respiratory Disease (CRD)
Turkey | 13 | Chronic Respiratory Disease (CRD)
Buffalo | 14 | Coccidiosis
Cattle | 14 | Coccidiosis
Goat | 14 | Coccidiosis
Sheep | 14 | Coccidiosis
Horse | 14 | Coccidiosis
Cat | 14 | Coccidiosis
Dog | 14 | Coccidiosis
Pig | 14 | Coccidiosis
Chicken | 14 | Coccidiosis
Duck | 14 | Coccidiosis
Goose | 14 | Coccidiosis
Myna | 14 | Coccidiosis
Pigeon | 14 | Coccidiosis
Quail | 14 | Coccidiosis
Turkey | 14 | Coccidiosis
Chicken | 15 | Colibacillosis (E. coli Infection)
Duck | 15 | Colibacillosis (E. coli Infection)
Goose | 15 | Colibacillosis (E. coli Infection)
Myna | 15 | Colibacillosis (E. coli Infection)
Pigeon | 15 | Colibacillosis (E. coli Infection)
Quail | 15 | Colibacillosis (E. coli Infection)
Turkey | 15 | Colibacillosis (E. coli Infection)
Goat | 16 | Contagious Caprine Pleuropneumonia
Buffalo | 17 | Dermatophilosis
Cattle | 17 | Dermatophilosis
Goat | 17 | Dermatophilosis
Sheep | 17 | Dermatophilosis
Horse | 17 | Dermatophilosis
Cat | 17 | Dermatophilosis
Dog | 17 | Dermatophilosis
Pig | 17 | Dermatophilosis
Chicken | 18 | Duck Cholera
Duck | 18 | Duck Cholera
Goose | 18 | Duck Cholera
Myna | 18 | Duck Cholera
Pigeon | 18 | Duck Cholera
Quail | 18 | Duck Cholera
Turkey | 18 | Duck Cholera
Chicken | 19 | Duck Plague (Duck Enteritis Virus)
Duck | 19 | Duck Plague (Duck Enteritis Virus)
Goose | 19 | Duck Plague (Duck Enteritis Virus)
Myna | 19 | Duck Plague (Duck Enteritis Virus)
Pigeon | 19 | Duck Plague (Duck Enteritis Virus)
Quail | 19 | Duck Plague (Duck Enteritis Virus)
Turkey | 19 | Duck Plague (Duck Enteritis Virus)
Chicken | 20 | Egg Drop Syndrome (EDS)
Duck | 20 | Egg Drop Syndrome (EDS)
Goose | 20 | Egg Drop Syndrome (EDS)
Myna | 20 | Egg Drop Syndrome (EDS)
Pigeon | 20 | Egg Drop Syndrome (EDS)
Quail | 20 | Egg Drop Syndrome (EDS)
Turkey | 20 | Egg Drop Syndrome (EDS)
Buffalo | 21 | Ephemeral Fever
Cattle | 21 | Ephemeral Fever
Buffalo | 22 | Foot and Mouth Disease (FMD)
Cattle | 22 | Foot and Mouth Disease (FMD)
Goat | 22 | Foot and Mouth Disease (FMD)
Sheep | 22 | Foot and Mouth Disease (FMD)
Pig | 22 | Foot and Mouth Disease (FMD)
Buffalo | 23 | Foot rot
Cattle | 23 | Foot rot
Goat | 23 | Foot rot
Sheep | 23 | Foot rot
Horse | 23 | Foot rot
Pig | 23 | Foot rot
Chicken | 24 | Fowl Cholera
Duck | 24 | Fowl Cholera
Goose | 24 | Fowl Cholera
Myna | 24 | Fowl Cholera
Pigeon | 24 | Fowl Cholera
Quail | 24 | Fowl Cholera
Turkey | 24 | Fowl Cholera
Chicken | 25 | Fowl Pox
Duck | 25 | Fowl Pox
Goose | 25 | Fowl Pox
Myna | 25 | Fowl Pox
Pigeon | 25 | Fowl Pox
Quail | 25 | Fowl Pox
Turkey | 25 | Fowl Pox
Buffalo | 26 | Gangrene
Cattle | 26 | Gangrene
Goat | 26 | Gangrene
Sheep | 26 | Gangrene
Horse | 26 | Gangrene
Cat | 26 | Gangrene
Dog | 26 | Gangrene
Pig | 26 | Gangrene
Chicken | 27 | Gangrenous Dermatitis
Duck | 27 | Gangrenous Dermatitis
Goose | 27 | Gangrenous Dermatitis
Myna | 27 | Gangrenous Dermatitis
Pigeon | 27 | Gangrenous Dermatitis
Quail | 27 | Gangrenous Dermatitis
Turkey | 27 | Gangrenous Dermatitis
Sheep | 28 | Gid Disease (Cerebral coenurosis)
Horse | 28 | Gid Disease (Cerebral coenurosis)
Goat | 29 | Goat Pox
Buffalo | 30 | Hemorrhagic Septicemia (HS)
Cattle | 30 | Hemorrhagic Septicemia (HS)
Goat | 30 | Hemorrhagic Septicemia (HS)
Sheep | 30 | Hemorrhagic Septicemia (HS)
Horse | 30 | Hemorrhagic Septicemia (HS)
Pig | 30 | Hemorrhagic Septicemia (HS)
Buffalo | 31 | Hump Sore
Cattle | 31 | Hump Sore
Chicken | 32 | Infectious Bursal Disease (IBD)
Duck | 32 | Infectious Bursal Disease (IBD)
Goose | 32 | Infectious Bursal Disease (IBD)
Myna | 32 | Infectious Bursal Disease (IBD)
Pigeon | 32 | Infectious Bursal Disease (IBD)
Quail | 32 | Infectious Bursal Disease (IBD)
Turkey | 32 | Infectious Bursal Disease (IBD)
Chicken | 33 | Infectious Coryza
Duck | 33 | Infectious Coryza
Goose | 33 | Infectious Coryza
Moyana | 33 | Infectious Coryza
Pegion | 33 | Infectious Coryza
Quail | 33 | Infectious Coryza
Turkey | 33 | Infectious Coryza
Chicken | 34 | Infectious Laryngotracheitis Virus (ILT)
Duck | 34 | Infectious Laryngotracheitis Virus (ILT)
Goose | 34 | Infectious Laryngotracheitis Virus (ILT)
Myna | 34 | Infectious Laryngotracheitis Virus (ILT)
Pigeon | 34 | Infectious Laryngotracheitis Virus (ILT)
Quail | 34 | Infectious Laryngotracheitis Virus (ILT)
Turkey | 34 | Infectious Laryngotracheitis Virus (ILT)
Buffalo | 36 | Lice Infestation
Cattle | 36 | Lice Infestation
Goat | 36 | Lice Infestation
Sheep | 36 | Lice Infestation
Horse | 36 | Lice Infestation
Cat | 36 | Lice Infestation
Dog | 36 | Lice Infestation
Pig | 36 | Lice Infestation
Chicken | 36 | Lice Infestation
Duck | 36 | Lice Infestation
Goose | 36 | Lice Infestation
Myna | 36 | Lice Infestation
Pigeon | 36 | Lice Infestation
Quail | 36 | Lice Infestation
Turkey | 36 | Lice Infestation
Buffalo | 37 | Liver Fluke
Cattle | 37 | Liver Fluke
Goat | 37 | Liver Fluke
Sheep | 37 | Liver Fluke
Horse | 37 | Liver Fluke
Cat | 37 | Liver Fluke
Dog | 37 | Liver Fluke
Pig | 37 | Liver Fluke
Chicken | 38 | Malnutrition
Duck | 38 | Malnutrition
Goose | 38 | Malnutrition
Myna | 38 | Malnutrition
Pigeon | 38 | Malnutrition
Quail | 38 | Malnutrition
Turkey | 38 | Malnutrition
Buffalo | 40 | Mastitis
Cattle | 40 | Mastitis
Goat | 40 | Mastitis
Sheep | 40 | Mastitis
Horse | 40 | Mastitis
Cat | 40 | Mastitis
Dog | 40 | Mastitis
Pig | 40 | Mastitis
Buffalo | 41 | Milk Fever
Cattle | 41 | Milk Fever
Buffalo | 42 | Mite Infestation
Cattle | 42 | Mite Infestation
Goat | 42 | Mite Infestation
Sheep | 42 | Mite Infestation
Horse | 42 | Mite Infestation
Cat | 42 | Mite Infestation
Dog | 42 | Mite Infestation
Pig | 42 | Mite Infestation
Chicken | 42 | Mite Infestation
Duck | 42 | Mite Infestation
Goose | 42 | Mite Infestation
Moyana | 42 | Mite Infestation
Pegion | 42 | Mite Infestation
Quail | 42 | Mite Infestation
Turkey | 42 | Mite Infestation
Chicken | 43 | Mycoplasmosis
Duck | 43 | Mycoplasmosis
Goose | 43 | Mycoplasmosis
Moyana | 43 | Mycoplasmosis
Pegion | 43 | Mycoplasmosis
Quail | 43 | Mycoplasmosis
Turkey | 43 | Mycoplasmosis
Buffalo | 44 | Navel Ill
Cattle | 44 | Navel Ill
Goat | 44 | Navel Ill
Sheep | 44 | Navel Ill
Horse | 44 | Navel Ill
Pig | 44 | Navel Ill
Chicken | 45 | Necrotic Enteritis
Duck | 45 | Necrotic Enteritis
Goose | 45 | Necrotic Enteritis
Moyana | 45 | Necrotic Enteritis
Pegion | 45 | Necrotic Enteritis
Quail | 45 | Necrotic Enteritis
Turkey | 45 | Necrotic Enteritis
Chicken | 46 | Newcastle Disease
Duck | 46 | Newcastle Disease
Goose | 46 | Newcastle Disease
Moyana | 46 | Newcastle Disease
Pegion | 46 | Newcastle Disease
Quail | 46 | Newcastle Disease
Turkey | 46 | Newcastle Disease
Goat | 47 | Pesti des Petits Ruminants
Sheep | 47 | Pesti des Petits Ruminants
Buffalo | 48 | Rabies
Cattle | 48 | Rabies
Goat | 48 | Rabies
Sheep | 48 | Rabies
Horse | 48 | Rabies
Cat | 48 | Rabies
Dog | 48 | Rabies
Pig | 48 | Rabies
Buffalo | 49 | Ringworm (Dermatophytosis)
Cattle | 49 | Ringworm (Dermatophytosis)
Goat | 49 | Ringworm (Dermatophytosis)
Sheep | 49 | Ringworm (Dermatophytosis)
Horse | 49 | Ringworm (Dermatophytosis)
Cat | 49 | Ringworm (Dermatophytosis)
Dog | 49 | Ringworm (Dermatophytosis)
Pig | 49 | Ringworm (Dermatophytosis)
Buffalo | 50 | Round Worm
Cattle | 50 | Round Worm
Goat | 50 | Round Worm
Sheep | 50 | Round Worm
Horse | 50 | Round Worm
Cat | 50 | Round Worm
Dog | 50 | Round Worm
Pig | 50 | Round Worm
Buffalo | 51 | Ruminal Tympany/ Bloat
Cattle | 51 | Ruminal Tympany/ Bloat
Goat | 51 | Ruminal Tympany/ Bloat
Sheep | 51 | Ruminal Tympany/ Bloat
Chicken | 52 | Salmonellosis
Duck | 52 | Salmonellosis
Goose | 52 | Salmonellosis
Moyana | 52 | Salmonellosis
Pegion | 52 | Salmonellosis
Quail | 52 | Salmonellosis
Turkey | 52 | Salmonellosis
Sheep | 53 | Sheep Pox
Cattle | 54 | Stringhalt
Buffalo | 55 | Tape Worm
Cattle | 55 | Tape Worm
Goat | 55 | Tape Worm
Sheep | 55 | Tape Worm
Horse | 55 | Tape Worm
Cat | 55 | Tape Worm
Dog | 55 | Tape Worm
Pig | 55 | Tape Worm
Buffalo | 56 | Teat Sore
Cattle | 56 | Teat Sore
Goat | 56 | Teat Sore
Sheep | 56 | Teat Sore
Horse | 56 | Teat Sore
Cat | 56 | Teat Sore
Dog | 56 | Teat Sore
Pig | 56 | Teat Sore
Buffalo | 57 | Tetanus
Cattle | 57 | Tetanus
Goat | 57 | Tetanus
Sheep | 57 | Tetanus
Horse | 57 | Tetanus
Cat | 57 | Tetanus
Dog | 57 | Tetanus
Pig | 57 | Tetanus
Buffalo | 58 | Theileriosis
Cattle | 58 | Theileriosis
Goat | 58 | Theileriosis
Sheep | 58 | Theileriosis
Horse | 58 | Theileriosis
Cat | 58 | Theileriosis
Dog | 58 | Theileriosis
Pig | 58 | Theileriosis
Buffalo | 59 | Tick Infestation
Cattle | 59 | Tick Infestation
Goat | 59 | Tick Infestation
Sheep | 59 | Tick Infestation
Horse | 59 | Tick Infestation
Cat | 59 | Tick Infestation
Dog | 59 | Tick Infestation
Pig | 59 | Tick Infestation
Chicken | 60 | Worm Infestation
Duck | 60 | Worm Infestation
Goose | 60 | Worm Infestation
Myna | 60 | Worm Infestation
Pigeon | 60 | Worm Infestation
Quail | 60 | Worm Infestation
Turkey | 60 | Worm Infestation
Dog | 61 | Canine Distemper
Cattle | 62 | Lumpy Skin Disease
Buffalo | 63 | Aspiration Pneumonia
Cattle | 63 | Aspiration Pneumonia
Goat | 63 | Aspiration Pneumonia
Sheep | 63 | Aspiration Pneumonia
Horse | 63 | Aspiration Pneumonia
Dog | 63 | Aspiration Pneumonia
Cat | 63 | Aspiration Pneumonia
Pig | 64 | Classical Swine fever
Chicken | 65 | Marek's Disease
Cat | 66 | Feline Panleukopenia

**Comment by yokat** [comment]
This is the data from BAHIS master data review from Taifur bhai

**Comment by yokat** [comment]
Dear @taifur-bau 
https://docs.google.com/spreadsheets/d/1inZYND7AEIboJW6OooHYxv0WWq-YhSV_oYfFpXP-GAc/edit?usp=sharing
I have created a list of all "top_diseases" entries in that link before. I added columns, with "keep" and "remove", and also one with "rename". Can you please go through the 227 entries and comment, how to handle each entry. Thank you!
iko

**Comment by mixmixmix** [comment]
https://github.com/road86/bahis-dash/blob/main/prep_data.py - this needs to be moved here from https://github.com/road86/bahis-dash/blob/40d78bff65f38a03897d21e0447316398dd2af8f/pages/dls.py#L44

**Comment by ChasNelson1990** [comment]
Is everything that needs to be actioned covered by road86/bahis-data#16? Or is there something unique to bahis-dash in this thread?

**Comment by mixmixmix** [comment]
I'll let Iko confirm, as it requires making sure that we don't do any more data prep in dash instead of data.

**Comment by yokat** [comment]
Yea https://github.com/road86/bahis-data/issues/16 can be used to cover this issue.
