### ISSUE TITLE
Transfer Solution from streamlit to plotly/dash

### ISSUE THREAD

**Issue by yokat** [road86/bahis-dash#17]
### Problem

Streamlit is easy but has limitations in customization. Also for publishing, streamlit does not seem to offer the best solution.

### Desired Solution

Develop a copy on basis of plotly/dash

**Comment by mixmixmix** [comment]
Hello Iko, could you create a new branch for this work? It would be good not to have any files relating to future version in main.

**Comment by yokat** [comment]
Created a branch called plotly-dash.
- Please check, if it works especially regarding the environmental variables
- Veryx messy content and is only to check, if it would run with the server.

**Comment by mixmixmix** [comment]
Thanks will take a look.

**Comment by yokat** [comment]
Roughly transferred. Details should be monitored in other issues.
