### ISSUE TITLE
Update to data including dec 19th 2022 and check continuousity

### ISSUE THREAD

**Issue by yokat** [road86/bahis-dash#19]
### Bug Description

Check if rate of reports remain constant during the last weeks.

### To Reproduce

4. See error.

**Comment by mixmixmix** [comment]
I think this relates to our data on the project not to the code of bahis-dash. I think you can just keep working in this one: https://github.com/road86/project-bahis/issues/133

**Comment by yokat** [comment]
data is now visible with the latest december 19th data.
