### ISSUE TITLE
Test Dash Plotly

### ISSUE THREAD

**Issue by yokat** [road86/bahis-dash#20]
### Test Description

There is a small code snipped based on plotly dash. I put it on git on a separate folder called plotly dash, where you can also find the virtual environment. (I modified the one used for the streamlit thing, so it has some unused assets and is bigger than necessary).
Once you have the new virtual environment activated. you can run the code with "python bahisdashplt.py" and you can see the result in http://127.0.0.1:8050/. It serves a Flask app.

### To Manually Test

Steps to carry out the test manually:
1.  Go to '...'
2.  Click on '...'
3.  Scroll down to '...'
4.  Check result.

**Comment by mixmixmix** [comment]
Hello Iko, could you create a new branch for this work? It would be good not to have any files relating to future version in `main`.

**Comment by mixmixmix** [comment]
If you could do one more change for me and I'll take a look soon, thanks! https://github.com/road86/bahis-dash/issues/17#issuecomment-1371147857

**Comment by mixmixmix** [comment]
It all works well and looks really nice :)

I did few minor changes to make it run on my computer with pipenv:
https://github.com/road86/bahis-dash/commit/67cea69f0afcb56278f2d6b57273e38781bf2afd

**Comment by ChasNelson1990** [comment]
@mixmixmix @yokat these pipenv and similar changes aren't actually in the plotly-dash branch for some reason? Because @WaliZaman and I just redid this all ourselves too. Please can we incorporate them into the plotly-dash branch so this doesn't get done for a third time?

**Comment by ChasNelson1990** [comment]
( @yokat you seem to have reverted those changes for some reason - but they are needed)
