### ISSUE TITLE
Geographic encoding

### ISSUE THREAD

**Issue by yokat** [road86/bahis-dash#24]
### Description of feature needing documentation

Is the format: e.g.  20466719	BATNATALI
always the way, that the first 2 digits are "division", the next numbers 3 and 4 are "district" and digit 5 and 6 are for "upazila", 7 and 8 are union encoding?
a) Can I take this for granted?
b) Can I take it for granted, that the entities are always within the next bigger region definition?

**Comment by WaliZaman** [comment]
b) yes. the geocode always contains the larger region.
a) down to union level you can take it for granted. If we go any lower, there are slight changes, e.g. mouzas have 3 digits instead of 2 (Barakanda union: 20 19 75 12; Haripur mouza: 20 19 75 12 455).
