### ISSUE TITLE
Check Upazila list

### ISSUE THREAD

**Issue by yokat** [road86/bahis-dash#30]
### Bug Description

- Wiki and data.humdata.org recalls a total number of 495 upazilas.
- In the exported data for the geoclusters, there are 545 entries with the location type 3 and a 6 digit number.
which is the main source for the geolocations and why is there a discrepancy in the exported file?

### To Reproduce

4. See error.

**Comment by yokat** [comment]
in the exported file: 
Barisal | 42
Chittagong | 114
Dhaka | 121
Khulna | 64
Mymensingh | 35
Rajshahi | 71
Rangpur | 58
Sylhet | 40

banglapedia has 39, 97, 120, 59, mymensingh did not have an entry, 70, rangpur had 21 U but 58 Districts, 38

**Comment by Paripurnaaaaa** [comment]
I didn't understand the last line. Can you explain a bit more of the numbers?

**Comment by yokat** [comment]
I was told, banglapedia has quite old data. The numbers were the number of Upazilas in a division I believe, but should only state, that I had problems finding a reliable source with the latest data.

**Comment by mixmixmix** [comment]
@yokat is this now sorted?

**Comment by yokat** [comment]
not yet. however the bigger number of upazilas can be be because of large cities containing several substructures. The priority is low at the moment, because no other person complained about it yet.

**Comment by yokat** [comment]
transferred to https://github.com/road86/bahis-data/issues/2
