### ISSUE TITLE
Setup pipenv on dash server

### ISSUE THREAD

**Issue by yokat** [road86/bahis-dash#39]
### Bug Description

Get pipenv running on dash server to be able to import environments.

### To Reproduce

4. See error.

**Comment by mixmixmix** [comment]
@yokat could you provide a list of the data files necessary for running the dashboard?
I get `FileNotFoundError: [Errno 2] No such file or directory: 'exported_data/Diseaselist.csv'` but I'm not sure which file this is as names have changed. You can also just update the processed files for me in a google drive.

**Comment by yokat** [comment]
Apologies:
https://drive.google.com/file/d/15NrcvwZeg39vc2_NpElxNMHUA_PaLNAg/view?usp=share_link

**Comment by yokat** [comment]
Current version comes with the following:
For preparation of geojsons, there is "prepgeojson.py". This uses geoBoundaries data from humdata.org and connects them with newbahis_geo_cluster.csv. It looks for the location in newbahis and checks in humdata shapes, if it is within the shape. A second run looks for identical names and cleans https://github.com/road86/bahis-dash/issues/40. I realized, there is a check missing, that it only cleans NAs... This creates an alternative set of geojson files.
I tried to reduce the data filesize with "prepquickdata.py" this reduces the data, but the viewing "dlsquick.py" is still in progress.
Furhermore, there is "prep_data.py", that was also modified by @mixmixmix. The timestamp of the last changes is later than his modifications because it seems I did again mistakes in merging repos. I hope I cleaned all of them correctly.
Despite, the dasboard uses "Diseaselist.csv" provided by @taifur-bau for grouping diseases.

**Comment by yokat** [comment]
The structure of the dashboard is
- index.py as the main entry point (start "python index.py")
- a navbar on top and pages in the corresponding folder. 
- with "dash.register..." commented out, the page can be excluded for viewing, as it has been done for "resp.py" for respiratory disease project.

**Comment by mixmixmix** [comment]
There is not need for a custom disease type csv. We should just keep up to date the master data (in-waiting) spreadsheet. I added column type after @taifur-bau https://docs.google.com/spreadsheets/d/1uSahdNKjalAOuO0Die77KUH0PC-exGF9P4b8uqYZccY/edit#gid=231029338

**Comment by yokat** [comment]
I keep the version for now, and will switch until we have a more or less official released spreadsheet for master data.

**Comment by mixmixmix** [comment]
It has been ubuntu's version of pipenv from the repository being borken. Installing globally using pip solved the issue

**Comment by mixmixmix** [comment]
I have tested the actual dashboard working. https://github.com/road86/bahis-dash/commit/06d8e37cc63a785570a8acc76fa30ccaf59e1c54

However I cannot guarantee that data processing scripts will work. Pipenv behaves bizarrely on my computer - when I'm not in the environment some libraries are unavailable, and work when I am in pipenv shell (e.g. it was `dash`). The trick is that those libraries were *not* in Pipfile!!! Hurray for Python being as always shait with dependency management 🤷 

@yokat please take a look at dashboard, and when running it make sure that on server it has `debug=False` set in `index.py` - it makes it work much faster.

**Comment by yokat** [comment]
Punctual testing resulted in a working new plotly dash version. Streamlit version is down.
