### ISSUE TITLE
Tiles are missing, geolocations are not matching

### ISSUE THREAD

**Issue by yokat** [road86/bahis-dash#40]
### Bug Description

some tiles are not shown and looking at the processed shape files, some geonumbers are missing, although the names should appear from the geolocations of bahis. However, the locations seem not to match with some of the shapefile and are therefore not matched. It has implications to all scripts of the dashboard and therfore need to be investigated further. 

### To Reproduce

4. See error.

**Comment by yokat** [comment]
is this a district:? 
	id	value	name	loc_type	parent	longitude	latitude	updated_at
15642	15637	107990	ZIANAGAR	3	1079	89.9343972493	22.4654562639	2021-07-26 17:47:25.000

**Comment by yokat** [comment]
manual setting of following upazilas:
Bandarban Sadar
Bijoynagar
Galachipa 
Haim Char 
Kalukhali
Mehendiganj 
Naikhongchhari
Paba 
Saltha
Tazumuddin
Zianagar

**Comment by yokat** [comment]
Yet unknown number contained in bahis and not in shape file
9 dhaka section not integrated

**Comment by yokat** [comment]
(Dhaka section not integrated -> only subtiles are representing dhaka)

**Comment by yokat** [comment]
Ramu wrongly sorted.

**Comment by yokat** [comment]
Neighboring:
Karmarkhanda
Ramu adjusted
Zapiganj has no data. Large cities not unfixed.

**Comment by yokat** [comment]
Only update NA fields, when checking names.

**Comment by yokat** [comment]
Checking names is working, because it chooses only selected cities to be updated.

**Comment by ChasNelson1990** [comment]
Relates road86/bahis-data#2

**Comment by yokat** [comment]
So let's transfer this to https://github.com/road86/bahis-data/issues/2 and close this one.
