### ISSUE TITLE
When Upazila is selected, while geoslider is larger it raises an error

### ISSUE THREAD

**Issue by yokat** [road86/bahis-dash#44]
### Bug Description

catch error

### To Reproduce

4. See error.

**Comment by ChasNelson1990** [comment]
This is essentially just the issue template text. Please edit the original post or close the ticket if it's no longer needed.

**Comment by yokat** [comment]
I didn't understand what you were referring to? Let's briefly chat about this at some point please.

**Comment by yokat** [comment]
no error generated, however no notice to user, as nothing changes. The user might wonder, why upazila can't be selected, while slider is set to district.
