### ISSUE TITLE
feat: show version number of dashboard and database

### ISSUE THREAD

**Issue by yokat** [road86/bahis-dash#73]
### Problem

To understand which version is used and until what date the database shows, both should be shown on the dashboard.

### Desired Solution

On the dashboad, eg: Version v1.0.0-1h3g5f7-76j4k21; Data up to 2023-03-17;
see also: https://www.conventionalcommits.org/en/v1.0.0/

**Comment by ChasNelson1990** [comment]
One idea for this today @yokat was to use the database files "last modified" as the database "version"
