### ISSUE TITLE
webpage is unaccessible, even when dashbaord seems to run under tmux

### ISSUE THREAD

**Issue by yokat** [road86/bahis-dash#79]
### Bug Description

The webpage shows unaccessible. 
Terminal still shows the timestamps so it seems to run.
I can't reproduce it locally 

### To Reproduce

I found the same case yesterday and simply restarted by killing python and restarting with python index.py.
This morning I encountered the same behaviour and couldn't access the dashboard again.
Currently I restarted it and it seems to run.

**Comment by yokat** [comment]
Tried the next day with the same outcome. Session seems to run, but the webpage is unaccessible.

**Comment by mixmixmix** [comment]
It wasn't working because as part of data updating script it has to kill the dashboard at night. It isn't possible to process the data on the current server so I'm disabling that script and the dashboard will run from tmux as normal now.
