### ISSUE TITLE
Build up time is slow

### ISSUE THREAD

**Issue by yokat** [road86/bahis-dash#8]
Create button to only build up reports and maps, once all settings have been made.

**Comment by yokat** [comment]
Alternative and slightly more concise solution:
Building up of the dashboard takes long. Research for possible solutions:
- preset links with already prepared data
- some sort of downloader for upazila only data

**Comment by yokat** [comment]
test with quick and dirty plotly dash solution

**Comment by yokat** [comment]
Advances made by reducing data load. Still slow and have to work alternative like caching/server side calculations, even less data?

**Comment by yokat** [comment]
- Check which tab is active and then calculate only this tab
- Check which data is needed, and whether all data needs to be taken alongside or only part of it 
- Load them only once and cache them
- Create scheme, to see how the data is used how and what parts to understand the connectivity
- Check methods to group/extract/search for data
- Check for datacopies, eventually delete unessessary variables
- investigate server side caching.

**Comment by yokat** [comment]
grouping takes long (Disease grouping 13s to max 2 for other parts)
caching is not the main problem

**Comment by ChasNelson1990** [comment]
@yokat - we have kind of solved this by moving to more specialised pages, correct? Can we close this or are there still on-going actions?

**Comment by yokat** [comment]
There can be more speed improving topics I could imagine, but it is probably up to the server migration to check, if further speed topics should be addressed. So I'll close this for now and could reopen, if it should be faster even when switched to the server.
