### ISSUE TITLE
Requested Information from 230619 Weekly meeting

### ISSUE THREAD

**Issue by yokat** [road86/bahis-dash#80]
### Description of feature needing documentation

It was requested to inform about the future dashboard infrastructure:

a) is it possible to include the future dashboard into the currently existing portal (http://bahis.dls.gov.bd/) ?
b) is it possible to use the same link to access the dashboard? 
c) In what frequency, data updates are planned - ranging from live - daily - weekly...
d) DLS had original design requests to the dashboard, which was partially realized in the portal. Especially the possibility to configure access rights to data and reports for specific users is seen as very useful. Would oauth be able to cover these features?

Please justify the answers.

**Comment by yokat** [comment]
A short update:

a) All report and data related topics will be put into a dashboard and it would be a link within the portal. The portal itself will continue to exist for geo and data manipulations as well as user administration, where rights management is connected to that
b) for that reason, it should be possible to use the link of the portal to access the dashboard, although it might run on a different server, also for maintenance reasons.

**Comment by ChasNelson1990** [comment]
> Would oauth be able to cover these features?

Yes. The idea will be that all users go to a single URL and sign in through an OAuth login page. That will redirect them to a landing page from which they can access the various services, inluding the portal -  see road86/project-bahis#204

**Comment by ChasNelson1990** [comment]
> In what frequency, data updates are planned - ranging from live - daily - weekly...

Daily. This is to prevent data reading occurring during peak data submission times and causing resource conflicts. Data will be read and processed every night whilst submissions are at their lowest.
