### ISSUE TITLE
When setting a specific date range, data is shown for all geolocations

### ISSUE THREAD

**Issue by ChasNelson1990** [road86/bahis-dash#91]
### Bug Description

When setting a specific date range in, for example, the DLS view, data is shown for all geolocations, i.e. for the correct dates but no longer for any pre-selected geographies.

### To Reproduce

1. Go to DLS view
2. Set an upazilla
3. Set a date range
4. See more data than you expect!

### Expected Behaviour

Setting the date range or geolocation should obey other pre-selected data.

**Comment by yokat** [comment]
closed with #104
